# Generated by Django 3.2.5 on 2021-07-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='published_at',
        ),
    ]
