# Generated by Django 3.2.5 on 2021-07-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210702_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='short_description',
        ),
    ]
