# Generated by Django 3.2.5 on 2021-07-02 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210702_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='long_description',
            field=models.CharField(default='My Long Description', max_length=560),
        ),
        migrations.AddField(
            model_name='book',
            name='short_description',
            field=models.CharField(default='My Short Description', max_length=280),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 21, 48, 26, 296505, tzinfo=utc), verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='My Title', max_length=280),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=models.CharField(default='My Content For The Chapter', max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(default='My Chapter Name', max_length=280),
        ),
    ]
