# Generated by Django 3.2.5 on 2021-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210702_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
