# Generated by Django 3.2.5 on 2021-07-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20210703_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
