# Generated by Django 3.2.5 on 2021-07-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210703_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='votes',
            new_name='score',
        ),
    ]
